/******************************************************************************************************************************************************************************************************\
 *** 
 *** Simulink model       : IO_CANII03AD5D24CNV_OSM_CSKN_10_egkn_EP
 *** TargetLink subsystem : IO_CANII03AD5D24CNV_OSM_CSKN_10_egkn_EP/CANII03AD5D24CNV_OSM_CSKN
 *** Codefile             : io-canii03ad5d24cnv-osm-cskn-1.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2026-06-05 16:01:49
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : omit all shifts
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 2147483647
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 2147483647
 *** Line break limit                         : 200
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.3\matlab\tl\config\codegen\cconfig.xml
 *** Root style sheet                         : C:\eagle\toolbox4x\RE\hook\stylesheet\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS         CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1            CANII03AD5D24CNV_OSM_CSKN
 *** Sa2            CANII03AD5D24CNV_OSM_CSKN/If_fc
 *** Sa3            CANII03AD5D24CNV_OSM_CSKN/else_fc
 *** Sa4            CANII03AD5D24CNV_OSM_CSKN/If_fc/rireki6
 *** Sa5            CANII03AD5D24CNV_OSM_CSKN/If_fc/rireki6/Model Info
 *** Sa6            CANII03AD5D24CNV_OSM_CSKN/else_fc/rireki6
 *** Sa7            CANII03AD5D24CNV_OSM_CSKN/else_fc/rireki6/Model Info
 *** 
 *** SUBSYS         CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE        CORRESPONDING STATEFLOW NODE                                                                                DESCRIPTION
 *** 
 *** TargetLink version      : 4.3p3 from 16-Oct-2018
 *** Code generator version  : Build Id 4.3.0.27 from 2018-09-24 17:55:03
\******************************************************************************************************************************************************************************************************/

#ifndef IO_CANII03AD5D24CNV_OSM_CSKN_1_C
#define IO_CANII03AD5D24CNV_OSM_CSKN_1_C

/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/

#include "io-canii03ad5d24cnv-osm-cskn-1.h"

/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/

/******************************************************************************************************************************************************************************************************\
   EXT_SP_GLOBAL: flexible global variables (RAM) for EAGLE,WZAA | Width: 16
\******************************************************************************************************************************************************************************************************/
EXT_SP_GLOBAL UInt16	VU16srs_lat_g_fd_imrx;	
EXT_SP_GLOBAL UInt16	VU16srs_lat_g_fdrx;	
EXT_SP_GLOBAL UInt16	VU16srs_lon_g_fd_imrx;	
EXT_SP_GLOBAL UInt16	VU16srs_lon_g_fdrx;	
EXT_SP_GLOBAL UInt16	VU16srs_pitch_fdrx;	
EXT_SP_GLOBAL UInt16	VU16srs_roll_fdrx;	
EXT_SP_GLOBAL UInt16	VU16srs_ver_g_fdrx;	
EXT_SP_GLOBAL UInt16	VU16srs_yaw_fd_imrx;	

/******************************************************************************************************************************************************************************************************\
   GLOBAL: global variables (RAM) for EAGLE,WZAA | Width: 32
\******************************************************************************************************************************************************************************************************/
GLOBAL Float32	VF24blatgfd_s = 0.F;	 /* 
   MIN/MAX: -24.5 .. 24.4993
   Description: JINIT=0.0 */
GLOBAL Float32	VF24blongfd_s = 0.F;	 /* 
   MIN/MAX: -24.5 .. 24.4993
   Description: JINIT=0.0 */
GLOBAL Float32	VF24bpitchfd_s = 0.F;	 /* 
   MIN/MAX: -125 .. 124.996
   Description: JINIT=0.0 */
GLOBAL Float32	VF24brollfd_s = 0.F;	 /* 
   MIN/MAX: -125 .. 124.996
   Description: JINIT=0.0 */
GLOBAL Float32	VF24bvergfd_s = 0.F;	 /* 
   MIN/MAX: -24.5 .. 24.4993
   Description: JINIT=0.0 */
GLOBAL Float32	VF24byawfd_s = 0.F;	 /* 
   MIN/MAX: -125 .. 124.996
   Description: JINIT=0.0 */

/******************************************************************************************************************************************************************************************************\
   GLOBAL: global variables (RAM) for EAGLE,WZAA | Width: 16
\******************************************************************************************************************************************************************************************************/
GLOBAL Int16	VS15lat_grev = 0;	 /* 
   LSB: 0.001 OFF: 0 MIN/MAX: -32.768 .. 32.767
   Description: JINIT=0000 */
GLOBAL Int16	VS15lon_grev = 0;	 /* 
   LSB: 0.001 OFF: 0 MIN/MAX: -32.768 .. 32.767
   Description: JINIT=0000 */

/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/

/******************************************************************************************************************************************************************************************************\
 ***  FUNCTION:
 ***      J_canrv_03ad5d24_cnvt
 *** 
 ***  DESCRIPTION:
 ***      12MY
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      FLG                f_canrxok           
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\******************************************************************************************************************************************************************************************************/
void J_canrv_03ad5d24_cnvt(FLG f_canrxok)
{
   LOG_VAR(a, _f_canrxok, f_canrxok);
   LOG_VAR(a, _VU16srs_lat_g_fd_imrx, VU16srs_lat_g_fd_imrx);
   LOG_VAR(a, _VU16srs_lat_g_fdrx, VU16srs_lat_g_fdrx);
   LOG_VAR(a, _VU16srs_lon_g_fd_imrx, VU16srs_lon_g_fd_imrx);
   LOG_VAR(a, _VU16srs_lon_g_fdrx, VU16srs_lon_g_fdrx);
   LOG_VAR(a, _VU16srs_pitch_fdrx, VU16srs_pitch_fdrx);
   LOG_VAR(a, _VU16srs_roll_fdrx, VU16srs_roll_fdrx);
   LOG_VAR(a, _VU16srs_ver_g_fdrx, VU16srs_ver_g_fdrx);
   LOG_VAR(a, _VU16srs_yaw_fd_imrx, VU16srs_yaw_fd_imrx);
   if (f_canrxok != 0) {
      /* SLLocal: Default storage class for local variables | Width: 32 */
      Float32	Sa2_Sum5;	
      Float32	Sa2_Sum6;	
      Float32	Sa2_Sum7;	

      /* Sum: CANII03AD5D24CNV_OSM_CSKN/If_fc/Sum7
         # combined # Gain: CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate7
         # combined # CANII03AD5D24CNV_OSM_CSKN/If_fc/Rescaler5 */
      Sa2_Sum7 = (((Float32) VU16srs_pitch_fdrx) * 0.003814697265625F) - 125.F;

      /* Saturation: CANII03AD5D24CNV_OSM_CSKN/If_fc/saturate_out : Noname upperlimit : 124.996 lowerlimit : -inf2 */
      if (Sa2_Sum7 > 124.996F) {
         /* # combined # TargetLink outport: CANII03AD5D24CNV_OSM_CSKN/$BPITCHFD_S */
         VF24bpitchfd_s = 124.996F;
      }
      else {
         /* # combined # TargetLink outport: CANII03AD5D24CNV_OSM_CSKN/$BPITCHFD_S */
         VF24bpitchfd_s = Sa2_Sum7;
      }

      /* Sum: CANII03AD5D24CNV_OSM_CSKN/If_fc/Sum6
         # combined # Gain: CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate6
         # combined # CANII03AD5D24CNV_OSM_CSKN/If_fc/Rescaler4 */
      Sa2_Sum6 = (((Float32) VU16srs_roll_fdrx) * 0.003814697265625F) - 125.F;

      /* Saturation: CANII03AD5D24CNV_OSM_CSKN/If_fc/saturate_out : Noname upperlimit : 124.996 lowerlimit : -inf1 */
      if (Sa2_Sum6 > 124.996F) {
         /* # combined # TargetLink outport: CANII03AD5D24CNV_OSM_CSKN/$BROLLFD_S */
         VF24brollfd_s = 124.996F;
      }
      else {
         /* # combined # TargetLink outport: CANII03AD5D24CNV_OSM_CSKN/$BROLLFD_S */
         VF24brollfd_s = Sa2_Sum6;
      }

      /* Sum: CANII03AD5D24CNV_OSM_CSKN/If_fc/Sum5
         # combined # Gain: CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate5
         # combined # CANII03AD5D24CNV_OSM_CSKN/If_fc/Rescaler3 */
      Sa2_Sum5 = (((Float32) VU16srs_yaw_fd_imrx) * 0.003814697265625F) - 125.F;

      /* Saturation: CANII03AD5D24CNV_OSM_CSKN/If_fc/saturate_out : Noname upperlimit : 124.996 lowerlimit : -inf */
      if (Sa2_Sum5 > 124.996F) {
         /* # combined # TargetLink outport: CANII03AD5D24CNV_OSM_CSKN/$BYAWFD_S */
         VF24byawfd_s = 124.996F;
      }
      else {
         /* # combined # TargetLink outport: CANII03AD5D24CNV_OSM_CSKN/$BYAWFD_S */
         VF24byawfd_s = Sa2_Sum5;
      }

      /* Sum: CANII03AD5D24CNV_OSM_CSKN/If_fc/Sum4
         # combined # TargetLink outport: CANII03AD5D24CNV_OSM_CSKN/$BVERGFD_S
         # combined # Gain: CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate4
         # combined # CANII03AD5D24CNV_OSM_CSKN/If_fc/Rescaler2 */
      VF24bvergfd_s = (((Float32) VU16srs_ver_g_fdrx) * 0.0007476806640625F) - 24.5F;

      /* Sum: CANII03AD5D24CNV_OSM_CSKN/If_fc/Sum3
         # combined # TargetLink outport: CANII03AD5D24CNV_OSM_CSKN/$BLATGFD_S
         # combined # Gain: CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate3
         # combined # CANII03AD5D24CNV_OSM_CSKN/If_fc/Rescaler1 */
      VF24blatgfd_s = (((Float32) VU16srs_lat_g_fd_imrx) * 0.0007476806640625F) - 24.5F;

      /* Sum: CANII03AD5D24CNV_OSM_CSKN/If_fc/Sum
         # combined # TargetLink outport: CANII03AD5D24CNV_OSM_CSKN/$BLONGFD_S
         # combined # Gain: CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate
         # combined # CANII03AD5D24CNV_OSM_CSKN/If_fc/Rescaler */
      VF24blongfd_s = (((Float32) VU16srs_lon_g_fd_imrx) * 0.0007476806640625F) - 24.5F;

      /* Reference of merge block: $LAT_GREV1 CANII03AD5D24CNV_OSM_CSKN/$LAT_GREV1
         update of variable(s) associated with CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname    
         gain : immediate1
         CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate1: Omitted upper saturation
         CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate1: Omitted lower saturation
         # combined # Gain: CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate1
         CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate1: Omitted upper saturation
         CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate1: Omitted lower saturation
         # combined # Sum: CANII03AD5D24CNV_OSM_CSKN/If_fc/Sum1
         CANII03AD5D24CNV_OSM_CSKN/If_fc/Sum1: Omitted upper saturation
         CANII03AD5D24CNV_OSM_CSKN/If_fc/Sum1: Omitted lower saturation */
      VS15lat_grev = (Int16) (((((Int32) VU16srs_lat_g_fdrx) - 32768) * 625) / ((Int32) 8192));

      /* Reference of merge block: $LON_GREV1 CANII03AD5D24CNV_OSM_CSKN/$LON_GREV1
         update of variable(s) associated with CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname    
         gain : immediate2
         CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate2: Omitted upper saturation
         CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate2: Omitted lower saturation
         # combined # Gain: CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate2
         CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate2: Omitted upper saturation
         CANII03AD5D24CNV_OSM_CSKN/If_fc/out : Noname     gain : immediate2: Omitted lower saturation
         # combined # Sum: CANII03AD5D24CNV_OSM_CSKN/If_fc/Sum2
         CANII03AD5D24CNV_OSM_CSKN/If_fc/Sum2: Omitted upper saturation
         CANII03AD5D24CNV_OSM_CSKN/If_fc/Sum2: Omitted lower saturation */
      VS15lon_grev = (Int16) (((((Int32) VU16srs_lon_g_fdrx) - 32768) * 625) / ((Int32) 8192));
   }
   else {
      /* Reference of merge block: $LAT_GREV1 CANII03AD5D24CNV_OSM_CSKN/$LAT_GREV1
         update of variable(s) associated with CANII03AD5D24CNV_OSM_CSKN/else_fc/Constant1 */
      VS15lat_grev = 0;

      /* Reference of merge block: $LON_GREV1 CANII03AD5D24CNV_OSM_CSKN/$LON_GREV1
         update of variable(s) associated with CANII03AD5D24CNV_OSM_CSKN/else_fc/Constant3 */
      VS15lon_grev = 0;
   }
   LOG_VAR(a, _VF24bpitchfd_s, VF24bpitchfd_s);
   LOG_VAR(a, _VF24brollfd_s, VF24brollfd_s);
   LOG_VAR(a, _VF24byawfd_s, VF24byawfd_s);
   LOG_VAR(a, _VF24bvergfd_s, VF24bvergfd_s);
   LOG_VAR(a, _VF24blatgfd_s, VF24blatgfd_s);
   LOG_VAR(a, _VF24blongfd_s, VF24blongfd_s);
   LOG_VAR(a, _VS15lat_grev, VS15lat_grev);
   LOG_VAR(a, _VS15lon_grev, VS15lon_grev);
}

/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
#endif /* IO_CANII03AD5D24CNV_OSM_CSKN_1_C */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
